### ISSUE TITLE
Add user's list of reviews in profile page

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#11]
A users profile should have list of all annotations, tags and ratings they did

**Comment by relwell** [comment]
👍

**Comment by relwell** [comment]
👍

**Comment by relwell** [comment]
👍

**Comment by williamhoos** [comment]
ideally extend configuration of the study page configuration tool to specify a different "location" for the tabs to allow easier configuration of the user's profile.  Study "tabs" section can be location "studies" and the user profile can be "profile"

**Comment by williamhoos** [comment]
merging to admin #124
