### ISSUE TITLE
Upgrade our location facet.

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#1128]
1. add 2500 and 3500 choices to the drop down so nationwide search can be done. and remove 5 and 10 miles to keep list shorter 
2.  fix the "x" in the crumbs within the facet (it works on the crumbsbar but not from within the facet
3. (there is also several flashes when selecting location
![image (21)](https://user-images.githubusercontent.com/2739321/134055469-7afa7d33-f49e-4534-b8d7-f2a88000efd3.png)
.

**Comment by jaynguyen0101** [comment]
#1 and #2 are good to go. Ignore #3 for now.
