### ISSUE TITLE
facet count values not correct

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#114]
the values showing in the parenthesis are not correct in facet drop downs

**Comment by williamhoos** [comment]
looks like the values showing in the facets are not related to the search (search for psoriasis shows top mesh term of glioblastoma)

**Comment by tibbs001** [comment]
Is this before or after it was switched back to the old database?

Can you provide some numbers that you expect it to be.

Thanks.

**Comment by williamhoos** [comment]
this is on dev too, so not related to database. I've seen this "flash" an updated value that looks appropriate for the new search and then it refreshes to the old value so something wrong with react/redux and what it is updating from server vs something local. Assume will fix in saga so not worth fixing now (depending on timing) - if too long till refactor is done, may need to revert change to the old way where loading of past top 10 was delayed. @relwell

**Comment by williamhoos** [comment]
closing for move to new version
