### ISSUE TITLE
facets

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#116]
Need to understand the facet counts. 
The numbers don't update in other factets when filtering on another facet. Thought this was the reason we couldn't do disjunctive. I'd probably rather gain disjunctive and lose accurate counts (which aren't accurate now for multi-facet filter)

**Comment by williamhoos** [comment]
Now it is disjunctive across all facet selections. Ideally need disjunctive within facet and conjunctive across facets:

ie selecting average rating 5 and 4 while also selecting phase 2 for phase should be:

WHERE (average_rating = 5 OR average_rating = 4) AND Phase = 'Phase 2'

**Comment by relwell** [comment]
Hey Willy,

I've researched this a bit more and the behavior seems to be what you're looking for. For instance, you can filter by tag "CancerCommonsGBM", and then filter by multiple status values such as "active, not recruiting" and "recruiting", and you will see the results change as expected. Is there something else you're looking for here?
