### ISSUE TITLE
study summary info

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#118]
Need the study summary info back as another tab or as header on page.

NCT ID
Type
Status
Primary Completion Date
Enrollment
Source

Is the "crowd" data over-ride working in refactor? Let's discuss if it has to be rebuilt (I'd prefer a side by side display of values instead of the over-ride checkbox like before)

**Comment by relwell** [comment]
The crowd data override is functional; I just seem to have forgotten the toggle.

The entire backend is designed to accommodate the wiki override. We could ask for the same set of data twice -- once with and once without.

**Comment by williamhoos** [comment]
looks great. let's discuss the display later of both side by side as well as default "open" for the table. Not closing but moving out of M5.1

**Comment by williamhoos** [comment]
Needs to change to expanded by default.
