### ISSUE TITLE
search address bar

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#120]
This address changes after entering in search box but reloading page or sending that link no longer submits the search term.

https://clinwiki-prod.herokuapp.com/search/TLR9

Let's discuss solution since broader issue of sharing faceted/sorted search is still desired.

**Comment by relwell** [comment]
there was a bit of a problem with how the search container interacted with location changes. i've found a solution, and will push the  change once i've implemented tests for it.

**Comment by williamhoos** [comment]
fixed, would like committ linked

**Comment by relwell** [comment]
https://github.com/clinwiki-org/cw-app/commit/11a05f7d1c97fe7a06062a473ebd7302c6027526
