### ISSUE TITLE
facet errors

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#121]
facets seem to filter from an old search or something? 

https://screencast.com/t/FfhsBUJiR9

**Comment by relwell** [comment]
your guess on this seems correct. it doesn't look like the updates to the facets are propagating when a search completes.

**Comment by relwell** [comment]
It looks like there was a bug related to how we're passing the query when we're loading new aggs. It was essentially an order of precedence issue related to whether we get the query from the redux store or the action being fired. Fixing the bug in this pot helped fix both this and the search address bar issue. I'll update the tests to make sure that this gets covered.
