### ISSUE TITLE
'Visible Options' for Crowd tags not working correctly

### ISSUE THREAD

**Issue by awestermann** [clinwiki-org/clinwiki#156]
The 'Visible Options' for the Facets seems to be working as it should, but I think it's not for the crowd tags. Ideally, it would work similar to the facets, in which if you select several options in the Visible Options, the others will not show up (like I did for the 'States' Facet on stocan.clinwiki.org). Currently, even though I've only selected 3 to be visible in the Crowd Tags (see Crowd Configuration picture attached), all of the crowd tags that are associated with the list of trials are showing up (see Crowd Tags picture). 
![StoCAN_CrowdConfiguration_9 23](https://user-images.githubusercontent.com/43178464/65470895-e8a62380-de21-11e9-90f9-1d509771cf95.png)
![StoCAN_CrowdTags_9 23](https://user-images.githubusercontent.com/43178464/65470901-ecd24100-de21-11e9-87e8-954f51f46aed.png)

**Comment by williamhoos** [comment]
fixed
