### ISSUE TITLE
facet blank

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#157]
enable inclusion of a "blank/null" option in facets so there is a way to identify when values are missing for a given facet are not present. 

Also, consider implementing exclude instead of include options in facets (ie return all values except the selected values)

can be part of #62

**Comment by williamhoos** [comment]
For clarification, first priority is figuring out how to add a "blank" value checkbox to every facet that allows also (or only) including the values that are blank for that facet.

In reference to a crowd value for the key "GBM Status" that has values of "Recurrent" and "Newly Diagnosed" and "Unknown" (which is a value stored).

Right now, there is no way to return these queries:
A) Only studies that have no value for GBM Status
B) All studies that have either "Recurrent" or No Value

UI View:
![image](https://user-images.githubusercontent.com/19411659/70278066-8d79a100-1781-11ea-9475-d24731b50f66.png)

Back end:
Unclear what it takes or issues, if any, for indexing

Notes:
Doesn't need to have the "counts" of blanks but would be nice if not expensive.

**Comment by williamhoos** [comment]
to clarify, only implementing the blank / not present now. The include/exclude will be solved manually for now (possibly with "select all") #230

**Comment by hifilorau** [comment]
@williamhoos @ericharding @micronix did we agree that nulls and blanks should be sent to the front end in the same bucket? Ie that nulls would be indexed as an empty string for front end consumption?

**Comment by williamhoos** [comment]
Have researched and this almost certainly should use the must_not and exists commands from elasticsearch at the top level of the query to return the count of values to include in the "blank" checkbox and then need to translate this into the search results query when/if selected.

This primarily applies to crowd values but can also apply to any facet/agg from the AACT datasource

**Comment by williamhoos** [comment]
Seems this isn't in latest code. Would like to have "_Missing_" as the value in UI unless there is a better choice. For alpha sort I'd prefer it to be last. Looking at ASCII, "~" sorts after z, so maybe "~Missing~"?

**Comment by williamhoos** [comment]
implemented with "Allow Missing"
