### ISSUE TITLE
Facet filter list for subsite (and Workflow) configuration not displaying all options

### ISSUE THREAD

**Issue by awestermann** [clinwiki-org/clinwiki#160]
The list of options for facets is not showing all possible options on subsites. Ex. the alsgoldenwest.clinwiki.org subsite (see attached pic)
![bug_facetlist](https://user-images.githubusercontent.com/43178464/66507814-bda80a80-ea84-11e9-8753-dbc27d62af90.png)
. The list is missing "Countries", "Browse Intervention Mesh Term", and "Rating_dimensions".  This impacts ability to only show facets of interest using the 'Only'  and 'All Except' options to filter.

**Comment by williamhoos** [comment]
Also note, the Worflow setup list of fields should be all available fields, not just the summary fields.

**Comment by williamhoos** [comment]
![image](https://user-images.githubusercontent.com/19411659/68424235-8d31ba00-0171-11ea-96e0-76407cd97270.png)

**Comment by awestermann** [comment]
'Country' is now in the facet filter list in dev, but is missing "Browse Intervention Mesh Term", and "Rating_dimensions" in the Search page configuration. 
![Screen Shot 2019-11-17 at 11 19 45 AM](https://user-images.githubusercontent.com/43178464/69010309-5d7e7100-092c-11ea-9bb3-238dade7cd7a.png)

**Comment by williamhoos** [comment]
fixed
