### ISSUE TITLE
Facet filter not displaying correctly

### ISSUE THREAD

**Issue by awestermann** [clinwiki-org/clinwiki#161]
When selecting 'Only' for Facet filtering, the function is working as it should and showing only the listed facets on the site, but when navigating back to the configuration page it displays 'All except' instead of 'Only'. (see pic) Not high priority.
![bug_filterdisplay](https://user-images.githubusercontent.com/43178464/66508921-dfa28c80-ea86-11e9-8fb9-f1f2725555e9.png)

**Comment by williamhoos** [comment]
To clarify, this is only a "display" issue in the subsite configuration page. the value of "only" for the filter is enabled as expected even though dropdown doesn't show the right value.
