### ISSUE TITLE
Add link to NCT number to clinicaltrials.gov page

### ISSUE THREAD

**Issue by awestermann** [clinwiki-org/clinwiki#162]
Add hyperlink on NCT ID number to corresponding clinicaltrials.gov page.
![NCTid_link](https://user-images.githubusercontent.com/43178464/66616482-c6343a00-eb85-11e9-9522-c494e4723f98.png)

**Comment by ericharding** [comment]
This fix should be live on https://staging.clinwiki.org.  
Thanks @rarbuthnot, our first Hacktoberfest contributor.

@awestermann  when you have a sec could you verify this does what you want and close the case?

**Comment by ericharding** [comment]
actually just check and re-open if this isn't working. 😄

**Comment by awestermann** [comment]
Thanks @rarbuthnot and @ericharding! I've checked and this is working as it should. My only thought is do we want it to open the clinicaltrials.gov page as a new page?

**Comment by williamhoos** [comment]
Agree we should do target=_blank for new tab

**Comment by awestermann** [comment]
When clicking on NCT number, it is no longer opening the clinicaltrials.gov as a new page. It was previously opening it as a new page, but for some reason has stopped.
