### ISSUE TITLE
Implement Additional Facet Formats

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#165]
Near term need:
Date Range filtering
Numeric filtering

A good toolkit looks like 
http://docs.searchkit.co/stable/components/navigation/range-filter.html

This ticket is to implement the searchkit to make those types available for use in facets, starting with adding the start date facet with a histogram range slider.

**Comment by williamhoos** [comment]
Adding specificity:
Two use cases:
1)
Would like to have the "Karnofsky Score Allowed" crowd facet on https://www.clinwiki.org/search/ANUr6Wwa to be a histogram range sorter using those values as a number. (http://docs.searchkit.co/stable/components/navigation/range-filter.html or dynamic if it has option to show histogram counts also http://docs.searchkit.co/stable/components/navigation/dynamic-range-filter.html) 

![image](https://user-images.githubusercontent.com/19411659/67146855-3f562000-f25d-11e9-8884-844c3b6e5ca8.png)


2) Start_Date for the study also a dynamic histogram range finder for date values

Note, currently the start_date is not on the list of facets but we will add this when needed. If the plumbing for a number and date range finder is in place, it can be applied to each study subsite via the configuration menu if the "Aggs display" "text" dropdown choice of "date" is wired to a date range finder and a "number" option is also created.

![image](https://user-images.githubusercontent.com/19411659/67146840-01f19280-f25d-11e9-8538-a63694521d84.png)

**Comment by williamhoos** [comment]
To clarify, would like to implement the date filter type first.

**Comment by hifilorau** [comment]
@williamhoos trying to figure out how this would work for both date and numeric. I know the date filter is higher priority but for example sake let's look at the karnofsky score. Would we be replacing the check box filters with the histogram style range filter? Doesn't seem like the current checkbox filer  would play nice with the range filter without  a lot of work/customization.
