### ISSUE TITLE
Improve history for wiki

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#166]
Would like to improve the change tracking diff history display. More like Wikipedia or another preferred example, hopefully something off the shelf? Ideally showing something like a table of history with date and who made change with ability to expand/click to the actual changes but show those changes more condensed like github shows in a long file, showing only the red/green changes and hiding (but allowing expansion of unchanged text). 

Wikipedia allows comparing across more distant versions which might be nice but not sure if necessary.

Sample history is https://www.clinwiki.org/study/NCT03785249/wiki/history

**Comment by williamhoos** [comment]
the clinicaltrials.gov history is pretty good if available as a model open source somewhere. The table of changes could be the date and id of changer to start.

https://clinicaltrials.gov/ct2/history/NCT03337698?A=1&B=19&C=Side-by-Side#StudyPageTop

**Comment by relwell** [comment]
It doesn't look clinicaltrials.gov exposes these changes in an API. We should probably focus on crowd changes exclusively for now. We can probably repopulate the set of changes in a given study by downloading all versions of the data from clinicaltrials.gov and diffing each study manually.

**Comment by williamhoos** [comment]
Agree. That was the intent. Just show the same history we already show but have a interface more like wikipedia or clinicaltrials.gov. Hopefully something is out there for showing a set of changes with user /date of change and ability to select which versions to show a diff for. The inline diff that clinicaltrials is easier to read but whatever is available will suffice to start
