### ISSUE TITLE
Add carriage returns to study page

### ISSUE THREAD

**Issue by awestermann** [clinwiki-org/clinwiki#167]
Carriage returns need to be added throughout the study pages, in particular the Eligibility Criteria field in the Recruitment tab (see picture) and the Detailed Description in the Descriptive tab (see picture). This will allow for reading these sections and finding relevant info more quickly.
![EligibilityCriteria](https://user-images.githubusercontent.com/43178464/66704844-b1b28780-ecd4-11e9-802c-839082365d47.png)
![DetailedDescription](https://user-images.githubusercontent.com/43178464/66704857-d7d82780-ecd4-11e9-8e15-c4678caf0875.png)

**Comment by Seanmclem** [comment]
seems like it's part of the data

**Comment by williamhoos** [comment]
Sean, thanks. It is in the data from graphiql with “\n”. We just need it to render in the html as carriage return. Thanks for looking.

A sample query showing eligibilityCriteria. 

query WikiPageQuery($nctId: String!) {
  study(nctId: $nctId) {
    nctId
    eligibilityCriteria
    briefTitle
    overallStatus
    createdAt
    updatedAt
    facilities {
      id
      city
      state
      country
      zip
    }
    interventions {
      id
      name
      description
    }
    wikiPage {
      content
      meta # tags and crowd values are here
      createdAt
      updatedAt
      # lay summary
      # references
    }
  }
}

## Parameters ###########################
{
  "nctId": "NCT00001595"
}

**Comment by williamhoos** [comment]
Just needs review and merge of PR and close.

**Comment by ericharding** [comment]
Merged in version 3
