### ISSUE TITLE
Fix contact info for trials

### ISSUE THREAD

**Issue by awestermann** [clinwiki-org/clinwiki#170]
Contact info isn't getting pulled in. Need to get that into the list that can be configured on one of the tabs. There are 2 places contact info is stored (within facilities which is all we are showing and in the "overall_contacts" table which we aren't pulling in currently. We need to fix it. Should be very fast to add it to the code and the list of configuration.

example:
https://clinicaltrials.gov/ct2/show/NCT00508573?displayxml=true
![image](https://user-images.githubusercontent.com/43178464/66964353-29f9af80-f02b-11e9-81d5-3b5adb2938e2.png)

**Comment by awestermann** [comment]
per Willy:
The queries from the db:

select * from overall_officials as oo
where nct_id = 'NCT00508573'

select * from central_contacts as cc
where nct_id = 'NCT00508573'

AACT Schema:
https://aact.ctti-clinicaltrials.org/static/documentation/aact_schema.png

_Not sure what else we are missing:
sponsors may not be right/available?_
_still need an update to the Arm/intervention structure (it's so messy it's hard to decide how to clean up but below is the query I wrote...needs to be confirmed what we want and converted to a ticket._

SELECT dg.group_type,dg.title,dg.description,i.name,i.intervention_type,i.description,ion.name as other_name
--i.*,ion.*,dg.*,dgi.*
FROM interventions i 
left outer join intervention_other_names ion 
on i.id = ion.intervention_id
left outer join design_group_interventions dgi 
on i.id = dgi.intervention_id
left outer join design_groups dg
on dgi.design_group_id = dg.id
where dg.nct_id = 'NCT02923921'
order by dg.group_type

**Comment by williamhoos** [comment]
covered in #333
