### ISSUE TITLE
Change subsite main page to be search results page

### ISSUE THREAD

**Issue by awestermann** [clinwiki-org/clinwiki#171]
Would like the subsites to go to search results page instead of current landing page. 
Example: would like the default landing page for AliveAndKickn.ClinWiki.org subsite: https://aliveandkickn.clinwiki.org/search, instead of this:

![Screen Shot 2019-10-18 at 4 54 11 PM](https://user-images.githubusercontent.com/43178464/67134640-fe5ffc00-f1c7-11e9-8ced-0dd5fcd750d0.png)

**Comment by awestermann** [comment]
This doesn't appear to be working for subsites.

**Comment by ericharding** [comment]
Does this one work for you?

https://site1.clinwiki.org

**Comment by ericharding** [comment]
Hmm.  Now that I typed out the link and clicked it it didn't work.  If I type that into the url bar it does. Browsers are weird.

**Comment by awestermann** [comment]
Very odd. Same thing is happening for me.

**Comment by williamhoos** [comment]
works on staging
