### ISSUE TITLE
Intervention table not listing interventions table

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#172]
This was working and linking to an intervention page. Now doesn't list specifics. Would like to know where we lost it and restore with refined query as discussed. 

Query below should be the table in the interventions section, eventually with the specific columns configurable but hard code to start is fine. Row of table should link to interventions page if still working.

When fixing, would like to identify where / how this got lost.

SELECT dg.group_type,dg.title,dg.description,i.name,i.intervention_type,i.description,ion.name as other_name
FROM interventions i 
left outer join intervention_other_names ion 
on i.id = ion.intervention_id
left outer join design_group_interventions dgi 
on i.id = dgi.intervention_id
left outer join design_groups dg
on dgi.design_group_id = dg.id
where dg.nct_id = 'NCT02923921'
order by dg.group_type

**Comment by ericharding** [comment]
This was lost with the study page customization.  The "Interventions" page is now a generic table of fields like Descriptive,Administrative,Recruitment.

**Comment by ericharding** [comment]
Deployed to staging.

**Comment by williamhoos** [comment]
looks good on staging
