### ISSUE TITLE
Mistyped subdomains or subdomains not on the list of created subsites should return error message

### ISSUE THREAD

**Issue by awestermann** [clinwiki-org/clinwiki#177]
Currently, if you mistype a subdomain, it appears to take you to the subdomain but really is just clinwiki.org.

Example, if trying to get to experimental.clinwiki.org, but type in [expiramental.clinwiki.org](https://expiramental.clinwiki.org) it seems like you get to the right subdomain but in actuality it's clinwiki.org. This should have returned an error message.

**Comment by williamhoos** [comment]
Make mistyped.clinwiki.org, if it isn't a valid subsite, give message that it is not a valid subtype (might as well give link "continue to clinwiki.org full site" link.

add *.server.clinwiki.org for staging and experimental to allow subsites to DNS
