### ISSUE TITLE
Address Index Refresh Delay

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#178]
Can we change index on update of studies to make it have no delay unless server load is too large?

Problem: When updating a study and returning to search page, behavior is inconsistent, even with refresh since there is a delay in index update.

**Comment by ericharding** [comment]
I looked into why this was the way it was.  The idea here is that if we have lots of traffic the 30 second delay would be able to batch multiple updates to a single study into one database update.  We're a long way off from that being needed but a bad idea. Lets try just having it drain the work queue every second and see how that feels.

**Comment by ericharding** [comment]
Tune to 5 seconds.
