### ISSUE TITLE
Code Review and deploy

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#180]
Review Code from Owera and CTG for approach. CTG needs to go to staging for testing, Owera is  on dev.

Two known issues with Owera branch https://github.com/clinwiki-org/clinwiki/tree/merged/owera-1

1) workflow broken with new study page layout - see if there is a quick fix
2) Seems all sections load at once so page is slower loading - suggestions for solution? First is hide sections by defuault (ideally add as checkbox for open/closed by default in subsite config) and only call for values/render if open. Could also just render first couple (that are visible on page, others load on scroll)

Have asked Owera to:
1) Finish having facet menu open by default and not hover over other content
2) change formatting of nct_ID hard code in card view to either format the header as first field in the list or make them all the same

**Comment by ericharding** [comment]
[x] Workflow
