### ISSUE TITLE
Change history log/report for subsite admins

### ISSUE THREAD

**Issue by awestermann** [clinwiki-org/clinwiki#191]
Want to create a report of wiki changes to trials which will be available to super admins and subsite admins.
Report will be used to identify and take action on any trials that need to be edited or (eventually) locked down for example. The change log report button ideally would be on the 'Sites' page (see below).

![Screen Shot 2019-11-01 at 2 04 12 PM](https://user-images.githubusercontent.com/43178464/68045994-2f086100-fcb1-11e9-920a-f840114d61b4.png)

**Comment by williamhoos** [comment]
If we have "date updated" for wiki content in index and available as a facet with date range filtering, then it would be possible to see list of changed studies in certain date range. Not exactly a change log but would partially solve.

**Comment by ericharding** [comment]
We do have a last updated time for all wiki content and timestamps on each diff.  We also have an updated timestamp on reviews.  We'd have to insert those into elasticsearch to be able to filter by a 'search'.  

If we inserted both dates into the index you could show a separate changed list for wiki vs reviews (vs other aspects?) but that is probably overly complex.  If we index the change date you could get a list of recently changed studies and drill down efficiently to the history of changes.
