### ISSUE TITLE
Presearch subite configuration rework

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#194]
This is a scoping issue for enabling the presearch as an alternative entry into searches.

Scoping is started in document linked below.

https://docs.google.com/presentation/d/1XTfp0U4uVZMhnnOXoGCgQfwBelmczD-9vOXQZN-jRsw/edit?usp=sharing

**Comment by CKH4** [comment]
# Presearch subsite configuration

## Configuring different search pages

When creating a site, a default search is created, this search is equivalent to the search created now. Search pages are listed in a table and configured on their own separate pages.

![configuring searches page](https://user-images.githubusercontent.com/13987924/68984231-ec7c7380-07dc-11ea-9413-4a604906b6c7.png "Configuring searches page")

## Editing a search page

The study format can be edited per search, but if you are not in a search the study page inherits from the default search.

![editing a search](https://user-images.githubusercontent.com/13987924/68984257-16ce3100-07dd-11ea-840a-39c9e06c2c4e.png "Editing a search")

## The search dashboard

Each search is listed on the search dashboard. Clicking on one of the searches navigates to the individual search or presearch page.

![search dashboard](https://user-images.githubusercontent.com/13987924/68984301-509f3780-07dd-11ea-8785-098c2ea41e5e.png "Search dashboard")

## Presearch in action

Each search page has its own url path (ex. `/search/default/`, `/search/foo/`) based on the name of the search.

![presearch page](https://user-images.githubusercontent.com/13987924/68984328-74fb1400-07dd-11ea-91ee-4a8fd6f92505.png "Presearch page")

**Comment by williamhoos** [comment]
1. "presearch in action" looks perfect 

Comments/Questions

1. To confirm, behavior of the facets will be identical to how they work now (when selecting a value, breadcrumb will appear, total results count will update, other facets will filter for available selected values)
2. Should we go with that same color scheme on the regular search facet sidebar or keep the dark colors?

**Comment by williamhoos** [comment]
2. The idea of the search dashboard listing the pre-searches is a good idea but I'm not sure how well that will fit the use case. Let's plan to add that later.

**Comment by williamhoos** [comment]
3. "Editing a search page" - I think the "difference" between pre-search and a "regular" search is 
"Regular search" - the facets show on the sidebar along with a search results grid
"Pre-search" - the facets sidebar is not shown and the chosen facets show in the area where the search results grid appears in a "regular search" and the "search button" transfers/maintains all of the breadcrumb values to the "regular search" 

Assuming above, 

1. It seems a toggle/radio button selecting between "regular" and "pre-search" is appropriate.
2. In pre-search, there is no reason to select the fields for display currently. The only configuration for the pre-search is which facets to show. All the facet configuration options currently available to the "regular search" (preselected values, visible options, order, display text) should also apply to the pre-search. 
3. Facets are open/expanded in pre-search - ideally, this would be implemented as an additional configuration option (open/close by default) so some advance facets could be closed by default in the pre-search. 
4. Having some facets open by default in the "regular search" would also be beneficial but out of scope for pre-search for now if it causes any problems implementing.

**Comment by williamhoos** [comment]
revised "spec" https://docs.google.com/presentation/d/1XTfp0U4uVZMhnnOXoGCgQfwBelmczD-9vOXQZN-jRsw/edit#slide=id.g65a6821c21_0_0

**Comment by williamhoos** [comment]
Further refinements discussed with @ericharding - working on implementation plan
