### ISSUE TITLE
bulk update broken

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#216]
Doesn't show the crowd facets at all.

![image](https://user-images.githubusercontent.com/19411659/69190663-e04f2980-0aee-11ea-99db-edd7cc2391be.png)

**Comment by ericharding** [comment]
This appears to be caused by some embedded spaces in one of the crowd labels.
"ALS Onset" vs " ALS Onset ".  I'll do a quick script to clean up the existing tag and then modify the tag code to make sure the string is trimmed before it gets stored.

**Comment by ericharding** [comment]
Interesting development. I manually fixed the study with the bad "ALS Onset" (NCT03090932) but now we get a new error from graphql saying the query is too large.  
"GraphQL error: Query has complexity of 450, which exceeds max complexity of 300"

**Comment by ericharding** [comment]
On experimental this seems to break when trying to update > 10k studies in one go. 

Elasticsearch::Transport::Transport::Errors::InternalServerError ([500] {"error":{"root_cause":[{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [15722]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"studies_development_20191220185303075","node":"T-mlJOHhRhOdbb-I2OHNRA","reason":{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [15722]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}}]},"status":500}):

app/services/search_service.rb:114:in `search'
app/graphql/mutations/bulk_query_update.rb:15:in `resolve'
app/controllers/graphql_controller.rb:13:in `execute'
app/middlewares/redirect.rb:45:in `call'
