### ISSUE TITLE
facet side bar on search page sometimes doesn't load

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#217]
haven't figured out how to reproduce but have seen a few times where facets never load, only shows a blank dark bar down side of search page

**Comment by ericharding** [comment]
Adding some more information for when we look at this.

This is the query that gets sent to elasticsearch. It takes about 14 seconds to run on staging.clinwiki.org. The time is definitely all spent inside elasticsearch not in the rails process.

time curl http://localhost:9200/studies_development/_search?pretty -H 'Content-Type: application/json' -d '{"aggs":{"facility_names":{"filter":{"bool":{"must":[{"bool":{"must":[]}}]}},"aggs":{"facility_names":{"terms":{"field":"facility_names","size":1000000,"order":{"_term":"asc"}},"aggs":{"agg_bucket_sort":{"bucket_sort":{"from":0,"size":25,"sort":[{"_key":{"order":"asc"}}]}}}}}}},"query":{"bool":{"must":{"query_string":{"query":"*"}},"filter":[{"bool":{"must":[]}}]}},"sort":[{"nct_id":"asc"}],"timeout":"11s","size":0,"from":0}'
