### ISSUE TITLE
Not all configured fields showing in summary section for WF and Study page

### ISSUE THREAD

**Issue by awestermann** [clinwiki-org/clinwiki#222]
Configured fields to 'Only' show in the summary section of a workflow are not displaying correctly. It is only showing a subset of the fields. 
![Screen Shot 2019-12-05 at 12 17 11 PM](https://user-images.githubusercontent.com/43178464/70275287-b3437d80-1762-11ea-8feb-6d12257254f3.png)
![Screen Shot 2019-12-05 at 12 16 45 PM](https://user-images.githubusercontent.com/43178464/70275298-b8083180-1762-11ea-81f3-2531ba21cec7.png)

**Comment by williamhoos** [comment]
I don't think the screen shot of the workflow configuration is explicitly related. If you don't specify anything, enrollment default to show but nctid is gone.

**Comment by williamhoos** [comment]
When we fix, let's document how this happened for the learning value

**Comment by williamhoos** [comment]
will fix when merging owera this weekend

**Comment by ericharding** [comment]
Fixed deployed to clinwiki production https://www.clinwiki.org/version  @awestermann

**Comment by ericharding** [comment]
In terms of documenting how this happened this never worked quite right.  This was an island of less generic code that got left behind when other stuff became more generic. You can see from the diff it's actually much simpler now than it was before.

**Comment by awestermann** [comment]
It appears that now the NCT ID is not showing up, nor the status and completion date (if listed) on the study page. For the WF, the summary section can now be configured, but the NCT ID lost the link out to the clinicaltrials.gov page on the WF page.
![Screen Shot 2019-12-17 at 12 15 05 PM](https://user-images.githubusercontent.com/43178464/71030944-48316980-20c7-11ea-8a96-8dd53443d847.png)
 
![Screen Shot 2019-12-17 at 7 07 11 AM](https://user-images.githubusercontent.com/43178464/71030800-043e6480-20c7-11ea-905e-5b51aa9e843e.png)

**Comment by ericharding** [comment]
It looks like `nct_id` is sometimes called `nctId` instead. I'll fix and push to prod tonight.

**Comment by ericharding** [comment]
This should be fixed now but I won't jinx it by closing the case until you've taken a look 😀

**Comment by awestermann** [comment]
It looks good to me! I tested the WF and took a look at the study page.
