### ISSUE TITLE
Override worfklow and bulk update values to display

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#225]
As short term solution, can we make the list of values in a workflow checkbox list contain all possible values for that key/label instead of only the available values in the query list of studies in the current workflow/search result. More ideal solution is issue #214 and label drop downs #96

**Comment by ericharding** [comment]
I'm pushing this up to prod as a quick fix.  There isn't an easy way to filter the set of facets that we want to see but *not* filter the values within those facets without making two queries. So with this change *all* the crowd facets and *all* the possible values get shown on the workflow which might be a little overwhelming but at least it isn't limiting.  Maybe tomorrow we can briefly discuss how to filter these down.

**Comment by williamhoos** [comment]
this fix works for now and looks good. Only issue missing "tags" facet in workflow is lost somehow.

**Comment by williamhoos** [comment]
Fix is try to delete the "tag" section and any special handling of anything "tags" related - and just treat "tags" like any other crowd key/value pair

**Comment by williamhoos** [comment]
this is fixed but intent is to return and allow setting visible options for workflows and crowd section
