### ISSUE TITLE
add message to maps card to explain that facility cannot be mapped  or partial matches

### ISSUE THREAD

**Issue by micronix** [clinwiki-org/clinwiki#228]

**Comment by williamhoos** [comment]
To document, I liked the idea of a red exclamation point icon near the number with a mouse-over message with wording "Facility cannot be mapped". Bonus points, maybe put the code for the partial match type/reason? Eventually we may have a "click to help resolve the address" that points to the crowd editable version of the address.

**Comment by williamhoos** [comment]
Adjusting scope:
Show "Not mapped" as described below in red
Show yellow version when address type is partial match (coordinate with Ramiro on data mapping to the warning).
