### ISSUE TITLE
restyle search cards to be consistent with cards from map view.

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#232]

**Comment by hifilorau** [comment]
@williamhoos i know we may move this/these to a new project board at some point, but until then am just going to put here in the event @blatde91 has downtime and wants to tackle. Might also be worth brief discussion and putting some thought into how we can improve the design and uX for the site & site view edit/create pages at some point.

**Comment by williamhoos** [comment]
I think this is done https://github.com/clinwiki-org/clinwiki/pull/249 and will be implemented with mailmerge
