### ISSUE TITLE
add the "loading" animation when autosuggest is loading

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#237]
Let's add the animation in the autosuggest area if the list is still loading while someone is typing (maybe open it up to the size of 4-5 rows of data and just show the loading or just show the list of facet headings that are showing on the autosuggest?

![image](https://user-images.githubusercontent.com/19411659/71728062-1c71eb80-2e0a-11ea-847b-1891b7c17828.png)

**Comment by blatde91** [comment]
I haven't noticed the autosuggest queries taking any time at all. Have you run into slow loading and have a way to recreate that?
