### ISSUE TITLE
Index additional Date fields and other fields

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#239]
Make new Facets available:
elasticsearch's indexed_at
studies.last_update_posted_date (already indexed)
wiki_pages.updated_at (need to index)
reviews.updated_at (need to index)

If they are aggregated at the mm/dd/yyyy level, they will hopefully just show in current facet checkbox type. It won't be ideal but it will function to filter dates.

**Comment by crocker** [comment]
@williamhoos @awestermann I have a few questions about this story. I'm still learning my way around so these might be obvious.

1. By "Make new facets available", I assume you are talking about adding more filtering/drill down options (Average Rating, Mesh Term, etc) on the left. Is that correct?
2. If my assumption for #1 is correct, do you have labels in mind for these?

**Comment by williamhoos** [comment]
That is correct. Note these are all configured via admin so they need to be
indexed and on the list. As far as the label, you can name them default
values from db. A feature we need to add is ability to specify a custom
label for each facet in the admin config. If any of that language doesn’t
make sense, Eric or Amy or I can clarify.

**Comment by bespinosa01** [comment]
last_changed_date
first_received_results
number_of_arms
number_of_groups
why_stopped
has_expanded_access
expanded_access_type_treatment
is_fda_regulated_drug/device
plan_to_share_ipd
design_outcome_measures

**Comment by Tonyynot14** [comment]
@williamhoos Do you want me to add all of the attributes in the above list to be indexed and have facets? This is the list Amy said in slack and wanted to make sure that is all of them, or if there were any others
