### ISSUE TITLE
bug with crowd values in autosuggest

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#251]
There is a bug with how breradcrumbs are applied for crowd aggs:

It looks like the value isn't getting translated correctly into the short link / query. It appears the crowd aggs are being grouped/coded into the JSON stored in the short_links table as par of the "agg_filters" group instead of "crowd_agg_filters" group. I have video if below description and links aren't enough.

In staging, below screen shot and crowd agg values is the error. The autosuggest selected value shows as a separate breadcrumb and is not interpreted as a crowd agg
http://staging.clinwiki.org/search/lRiJ3LBS
JSON from the short_links table:
{"agg_filters":[{"field":"browse_condition_mesh_terms","values":["Pancreatic   Neoplasms"]},{"field":"facility_cities","values":["Durham"]},{"field":"Disease   Group","values":["Breast   Cancer"]}],"crowd_agg_filters":[{"field":"Disease   Group","values":["Pancreatic"]}],"page":0,"page_size":25,"q":{"children":[],"key":"AND"},"sorts":[]}
--

This appears to be the correct coding (when selecting both values from the facets instead of one value from the autosuggest:

http://staging.clinwiki.org/search/CPHPuFsu

{"agg_filters":[{"field":"browse_condition_mesh_terms","values":["Pancreatic   Neoplasms","Triple Negative Breast   Neoplasms"]},{"field":"facility_cities","values":["Durham"]}],"crowd_agg_filters":[{"field":"Disease   Group","values":["Pancreatic","Breast   Cancer"]}],"page":0,"page_size":25,"q":{"children":[],"key":"AND"},"sorts":[]}
--

**Comment by blatde91** [comment]
https://github.com/clinwiki-org/clinwiki/pull/259

this pr fixes this issue
