### ISSUE TITLE
Google/Github auth/login

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#285]

**Comment by williamhoos** [comment]
I think #139 is the same so we can merge/close together.

**Comment by williamhoos** [comment]
google login looks good but it doesn't work on subsites on staging.

![image](https://user-images.githubusercontent.com/19411659/77025882-abea5d80-6968-11ea-9591-665e4e04d1d9.png)

**Comment by hifilorau** [comment]
Yeah, you have to add each subsite into the cloud client. Haven't seen if
there is an API for that but may be possible to do dynamically, but  not
sure if that was worth looking at, was thinking there wouldn't be a mass
number of subsites.

Guys have been working, save Tony, been sick for two days :(.  Will push
exp update tomorrow, will have some good stuff in it. Myself and one of our
other devs have been on a 36 hour bender been building an app that launches
tomorrow to help DPS deliver lunches to students so Im still completely
head down but hopefully finish up in a few hours, get a nights sleep and be
human again by tomorrow afternoon!
