### ISSUE TITLE
Crowd tags bug not returning results

### ISSUE THREAD

**Issue by awestermann** [clinwiki-org/clinwiki#291]
When filter using "StoCAN" or "Musella Foundation" or "ALS" crowd tags, results return as "No studies found". see links and picture below.

https://stocan.clinwiki.org/search/9ZG6nTRo
https://musella.clinwiki.org/search/qsj_T.YN
https://als.clinwiki.org/search/Cwcims6A

![Screen Shot 2020-02-25 at 10 37 44 AM](https://user-images.githubusercontent.com/43178464/75276849-ca22ca80-57bb-11ea-8cc1-a564f712023f.png)

**Comment by ericharding** [comment]
I think we can close this since the AACT is feeling better.
