### ISSUE TITLE
performance issues. 

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#336]
"Worst example is when typing in the presearch button text box (instructions too) - typing is way behind UI change. (it actually starts chewing my processor and turns on the fan, so something is very wrong)"

**Comment by hifilorau** [comment]
Suspect it's because the siteview provider is storing a ton of data right now. Probably need to create a siteview provider.

Think we need to start by changing siteview provider queries to query only the data we need and not all of the siteviews/sites

**Comment by hifilorau** [comment]
Scratch that. There are a ton of font-awesome and glyphicons being called on everykeystroke in the site name url and instruciton fields. they are defintiely causing typing issues.

**Comment by hifilorau** [comment]
Update from Brian. Siteview provider being called on each agg that is selected. In some of these there is 10-20 selected aggs just in presearch so siteprovider is getting called an absurd amount of times. Each one basically holding all config data for multiple siteviews.

**Comment by williamhoos** [comment]
Is that fixable? I was looking at the logs on experimental on the search
page when, for example, the results are off. I appears that it is still
running the results queries and retrieving all the data. Seems the config
should sync with what is requested. Also, the elastic query seems to have
criteria for every possible field / agg, even if not used, so may be a
related set of issues. Let’s assess the issue and ideate about the
solutions.
