### ISSUE TITLE
visible options under aggs freezes when opening

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#337]
Most likely a symptom of #336.

**Comment by williamhoos** [comment]
not sure they'd be related because the facet bar identical functionality works fine. Obviously past my expertise but sharing comment

**Comment by hifilorau** [comment]
@williamhoos which section did you mean when you said 'aggs'? Facet Bar, Presearch, or Autosuggest? They all have aggs. We were definitely experiencing some global issues today when all using at the same time and tyring to open various options,. Definitely think we know why the text inputs are laggy and they are not related to this (still trying to figure out why it's happening, seems like something to do with form handling in Bootstrap)... but there also seems to be alot of extra lagginess and slowness in general so thought you meant all of them.
