### ISSUE TITLE
Autosuggest config should be set to "only" instead of "all except"

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#339]

**Comment by bespinosa01** [comment]
Set the default to Only, instead of All Except. Currently I removed that selection field to match more presearch. @williamhoos let me know if the preference is to keep that or remove it.

**Comment by williamhoos** [comment]
Can you clarify what “ removed that selection field to match more
presearch” means?

**Comment by bespinosa01** [comment]
Removed the field that is highlighted by the red box to look like the second picture

![Screen Shot 2020-03-23 at 1 22 48 PM](https://user-images.githubusercontent.com/17464571/77349810-9464f900-6d09-11ea-9d09-3172253397bb.png)

**Comment by bespinosa01** [comment]
![Screen Shot 2020-03-23 at 1 22 29 PM](https://user-images.githubusercontent.com/17464571/77349895-b65e7b80-6d09-11ea-94d2-1a3ef9312f97.png)

**Comment by williamhoos** [comment]
thanks. looks good
