### ISSUE TITLE
Add ability to enter HTML into presearch instructions field.

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#371]

**Comment by hifilorau** [comment]
1. Add RichTextEditor component to presearch instructions in config.
2. Add RichTextEditor components for rendering of presearch instruction for reading markdown.

**Comment by blatde91** [comment]
@williamhoos I was able to implement this into Presearch today. The youtube video embed works, but only when you put it on a new line in the text editor.
![Screen Shot 2020-05-15 at 5 20 22 PM](https://user-images.githubusercontent.com/30156105/82097371-c4f55d80-96d0-11ea-9fbd-fadec3e026c0.png)
