### ISSUE TITLE
facet default sort order

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#372]
add ability to store the default sort order for a facet in the sub-site config area

most logical way to implement would be in the visible options dropdown, the selected sort order would be saved as the default for that facet (all controls in the user UI would still be adjusted just a default starting sort order)

![image](https://user-images.githubusercontent.com/19411659/77701648-2df00d00-6f8d-11ea-9fd7-f8303530837e.png)

Use case:
many of the "dirty" fields/facets like state, city - when they are set to default by numeric instead of text, will provide a more useful list - ie, if city is sorted by count, then after selecting Texas, Houston and Dallas sort to the top vs burried below a bunch of other cities that are in there from the multi-center studies.

**Comment by Tonyynot14** [comment]
https://github.com/clinwiki-org/clinwiki/compare/order_config

**Comment by Tonyynot14** [comment]
I made a branch that adds order config to site_view.rb. This stores the config in the way the front end passes the order which is aggOptionsSort: [{id: "key", desc: false}]

**Comment by williamhoos** [comment]
sort defaults of some facets doesn't seem to work in presearch, GBM status for sure, possibly others? Tags seems to work.

**Comment by williamhoos** [comment]
Looks fixed on staging
