### ISSUE TITLE
Bug in breadcrumbs. Removing crumb on profile page doesn't seem to retrigger results. like a preselected crumb is permanently selected.

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#394]

**Comment by hifilorau** [comment]
@blatde91 the issue we were experiencing trying to figure out why when we removed the userId from crumbs actually seems to be happening with any crumb when on searchPage not just the UserId like we suspected.

**Comment by williamhoos** [comment]
Seems like Bob was seeing some issues with what re-triggered queries. If Eric finishes merge tonight let’s try to get these changes into the merged branch and see what is causing the issue.
