### ISSUE TITLE
facet bar - crowdaggs dropdown box "only" vs "all except" - doesn't show saved value 

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#402]

**Comment by williamhoos** [comment]
@hifilorau this shows in testing? Does that mean it is on staging now? Which branch, is it a commit or a PR and do those reference this issue number and how are we confirming resolution? Maybe the commit or PR that resolves it references the issue for tracking?

**Comment by hifilorau** [comment]
@williamhoos good point. For now, and this probably needs some tweaking, means brian had finished it locally and that we've merged it into our feature branch and he's ready to work on another card. But it probably needs to mean it's actually on staging or experimental or whichever public branch we are deploying to. And agreed that it would be good practice to start referencing the issue number in the commits so that ultimately the PRs will be easier to track.

**Comment by hifilorau** [comment]
or at the very least we put in a PR for the fix.

**Comment by williamhoos** [comment]
@hifilorau If I'm reading "Testing" correctly, this is supposed to be on staging server right now.  I don't see where it is fixed. 

Screen shot of the default site_view settings, showing that both are set to "only" on the search page but the dropdown for the crowd aggs shows "all except" despite real value being "only"

![image](https://user-images.githubusercontent.com/19411659/78622488-3e3c9d80-7853-11ea-9589-5e3fbcf9918f.png)


![image](https://user-images.githubusercontent.com/19411659/78622500-485e9c00-7853-11ea-830d-d7b1f08e374d.png)

**Comment by hifilorau** [comment]
I believe I noted I was also going to put in Testing if we had an open PR
(#408)  to staging and that was the only other case I thought was
appropriate to use for "testing."  Also made a  card specifically on our
board nothing this this afternoon. Specifically also wanted to talk to Eric
more about what he though the best process was for merging this onslaught
of bug fixes the next couple.of days since I don't know specifically what
he is/was working on. Wanted to make sense to coordinate some with him on
getting all of these changes fixed and merged in the easiest way possible
without creating extra work for any of us.

**Comment by williamhoos** [comment]
Confirmed Done
