### ISSUE TITLE
results, it doesn't show the selected result type (why not just show in the dropdown like normal dropdowns - same with the button configs - why have button change values up above dropdown vs just show as selected in drowdown?

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#403]

**Comment by hifilorau** [comment]
easy fix but didn't

**Comment by williamhoos** [comment]
Not visible on staging. Show screen shot of it working if it has been pushed to staging.

![image](https://user-images.githubusercontent.com/19411659/78622709-de92c200-7853-11ea-88d4-7ff537449454.png)

**Comment by williamhoos** [comment]
confirmed
