### ISSUE TITLE
new numeric range facet shouldn't be date (need to make two types of facet fields - "date" the current date range behavior and make "number range" use a simple input box instead of date input type 

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#406]

**Comment by hifilorau** [comment]
@williamhoos any info on what broke in the merge? Or error messages? Possible that something else that got merged at the same time this PR was in caused a conflict but not quite sure yet.. @bespinosa01 is going to rebase again with up-to-date staging to double check but if you have any other info, let us know.

**Comment by williamhoos** [comment]
deployed and tested. Included fixes from PR #451 and commits 

https://github.com/clinwiki-org/clinwiki/commit/fc01c379317e46cee05374a3a2f541537830bea7
https://github.com/clinwiki-org/clinwiki/commit/19f7436b4bbd95b8ea9210a8f6ec0a30f744b15c
https://github.com/clinwiki-org/clinwiki/commit/229b1f450012ce911843aa87f3c9328da0d4f9bb
