### ISSUE TITLE
Home page search terms not added to search page

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#420]

**Comment by williamhoos** [comment]
confirm home.clinwiki.org works when submitting? Searching "covid" currently goes to "https://www.clinwiki.org/?q=covid"

seems it should probably go to something like: https://www.clinwiki.org/search?q=covid (and the interpreter should convert this to incorporate the q into the has and display the site default with the search term as a breadcrumb

**Comment by williamhoos** [comment]
This is implemented in #323 and PR #351 

However, would like to improve handling. The behavior should append the terms in the queytstring to the search hash, just as if it had been submitted in the "search within" box where we also show autosuggest. It should also work with any site_view and honor any other querystrings present for hash or sv (ie this link should ideally lead to this search result:

https://covid.clinwiki.org/search?sv=presearch&q=hydroxychloroquine

--->
https://covid.clinwiki.org/search?hash=vj0XbFOF&sv=presearch

Note the inclusion of the site's default search terms also. Right now this is the results which has cleared all terms except the value in q. https://covid.clinwiki.org/search?hash=SCR66iLl&sv=presearch

I also think the term should append if a hash is submitted, ie if submitting 
https://covid.clinwiki.org/search?hash=CcybxCnm&sv=presearch&q=hydroxychloroquine
---> result is
https://covid.clinwiki.org/search?hash=ouiI1E.y&sv=presearch

**Comment by williamhoos** [comment]
@hifilorau Did Anyone look at this and where does it fit in priority? Not sure if this deployed to prod yet but if it is on prod, it isn't working.
