### ISSUE TITLE
editing a site view freezes the site for me; unable to click anything and have to close and open new tab

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#422]

**Comment by hifilorau** [comment]
@awestermann this is on staging? Can you hit command + option + j next time this happens and let me know if there are any error messages and screenshot if so?

**Comment by awestermann** [comment]
Yes, it was on staging. It kept doing it to me earlier, but I'm not able to replicate it now (which is good I guess). I will keep testing and send along the error messages if I run across it again.
