### ISSUE TITLE
unable to create new site (tried with unique numbers, not just test3)

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#423]

**Comment by hifilorau** [comment]
haven't been able to recreate yet.

**Comment by williamhoos** [comment]
@awestermann needs to test this

**Comment by awestermann** [comment]
It is working now. I think the issue was user error on my part - I wasn't changing "default" under subdomain.

![Screen Shot 2020-04-09 at 1 11 37 PM](https://user-images.githubusercontent.com/43178464/78936746-035d8400-7a64-11ea-9376-c039c65ea661.png)
