### ISSUE TITLE
The workflow and bulk update facets have -99999999999 as a value - should be removed

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#441]
This appeared after adding the "allow missing" checkbox to facets on the facet bar and presearch area. "Allow Missing" doesn't apply to these other settings in workflow and bulk update.

Sample link and screen shot below

https://covid.clinwiki.org/study/NCT04276896/workflow?hash=xJICh0wT&sv=default

![image](https://user-images.githubusercontent.com/19411659/79050502-7bf54980-7bf8-11ea-9730-58713f905992.png)

**Comment by williamhoos** [comment]
The 99999 is still showing on staging and production for workflow, so that part of the issue was not fixed.

**Comment by relwell** [comment]
Can you help me understand the steps I need to take to get to the workflow section? It wasn't something I could find locally.

**Comment by williamhoos** [comment]
Sorry.

1. Set up a crowd value that starts with “WF_”
2. Do a search and include a selection of at least one value from the
workflow
3. Click on a study in those search results and the workflow section will
appear

I think that the fields will show in workflow by default but to configure
the workflow options, the “workflow” menu (same area as sites and profile)
for an admin role account.

We need to get a dev database that has all the configurations that can be
tested.
