### ISSUE TITLE
2. Add default styles from withTheme to the db on the site object.

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#454]
Need to update default object to better reflect the vars that we are actually using in our colors object.

**Comment by Tonyynot14** [comment]
Thinking about making the site have configuration options the same way site view does with a updates column in the database. It seems like it could be used the same way but to also update config options for the site starting with theme and colors. The only weird part is the naming of the class makes it feel like it is only for siteview (which is was but now would be used elsewhere) and some of the methods in the site model are almost exactly the same as siteview methods such as view and mutations.

**Comment by Tonyynot14** [comment]
https://github.com/clinwiki-org/clinwiki/compare/string_theme?expand=1
