### ISSUE TITLE
bad subsite addresses do not show an error page. 

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#483]
https://donkeys.clinwiki.org/ triggers error and https://donkey.clinwiki.org/search?hash=w2u8cgR2&s does not and instead routes to default site's default siteview. @Tonyynot14 can you check out redirect.rb and see if it's something there.

**Comment by Tonyynot14** [comment]
Willie told me to abandon working on this a while back and said Eric would solve the issue
