### ISSUE TITLE
Improve workflow and bulk update formatting to match presearch

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#505]
Goals is that the formatting of facets in workflow and bulk can use the same format styles for the facets as the presearch area on the search page. The color and font scheme of the facets and the wrapping behavior are the main goals.

This should not impact the behavior, only the styles, since both workflow and bulk have their own behaviors for the facet check/uncheck.

workflow is more important than bulk, so if you find any complications with bulk, skip it.

even more ideally, any special styles that apply to the div or the behaviors for wrapping, ideally can be abstracted to the single location in the them file and used in all 3 places?

**Comment by hifilorau** [comment]
Plan.

1. Move presearch themed wrapper and presearch card into our styled component library
2. Rename ThemedFacetCard.
3. Apply to workflow page from our styled components folder.
4. Apply to bulk edit page from sc folder. 
5. Reapply to presearch from our styled component page.

Then move onto #511

**Comment by williamhoos** [comment]
I think this is on experimental which is where I tested. If not, we can retest in staging.

 in bulk update area, new formatting doesn't scroll within a facet box, overflowing. Works fine in workflow and presearch so not sure why it's an issue for the same format use.

![image](https://user-images.githubusercontent.com/19411659/80779008-547b0800-8b38-11ea-95d7-677d01fe47fd.png)
