### ISSUE TITLE
Geolocation

### ISSUE THREAD

**Issue by relwell** [clinwiki-org/clinwiki#51]
1) Ingest lat long of facilities based on zip code
>> https://gist.github.com/erichurst/7882666
2) Add to index
3) Add functionality to search based on current location (or zip, if we have this in the database)

Filters for distance (miles)

**Comment by relwell** [comment]
👍 👍 👍

**Comment by williamhoos** [comment]
cover with maps for sites

**Comment by williamhoos** [comment]
closed and merged into #127
