### ISSUE TITLE
Change the display names of Wiki edits date range and email to somethinge more human readable.

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#510]
to Wiki Edit Date Range
& Wiki Edit User Email

![Screen Shot 2020-04-27 at 12 50 41 PM](https://user-images.githubusercontent.com/2739321/80398597-de4f7a80-8885-11ea-8982-2365217f2ce7.png)

**Comment by hifilorau** [comment]
Research into how to configure this.

**Comment by williamhoos** [comment]
fixed in another issue
