### ISSUE TITLE
Wiki_edits values (nested) are not showing up when breadcrumbs/filters are applied.

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#515]

**Comment by hifilorau** [comment]
`curl http://localhost:9200/studies_development/_search?pretty -H 'Content-Type: application/json' -d '{
  "aggs": {
    "wiki_page_edits": {
      "nested": {
        "path": "wiki_page_edits"
      },
      "aggs": {
        "wiki_page_edits.email": {
          "filter": {
            "bool": {
              "must": [
                {
                  "bool": {
                    "must": [
                      {
                        "bool": {
                          "filter": []
                        }
                      },
                      {
                        "bool": {
                          "filter": []
                        }
                      }
                    ]
                  }
                }
              ]
            }
          },
          "aggs": {
            "wiki_page_edits.email": {
              "terms": {
                "field": "wiki_page_edits.email",
                "size": 1000000,
                "order": {
                  "_term": "asc"
                },
                "missing": "-99999999999"
              },
              "aggs": {
                "agg_bucket_sort": {
                  "bucket_sort": {
                    "from": 0,
                    "size": 25,
                    "sort": [
                      {
                        "_key": {
                          "order": "asc"
                        }
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": "*"
          }
        },
        {
          "nested": {
            "path": "wiki_page_edits",
            "query": {
              "bool": {
                "should": []
              }
            }
          }
        },
        {
          "nested": {
            "path": "wiki_page_edits",
            "query": {
              "bool": {
                "should": {
                  "range": {
                    "wiki_page_edits.created_at": {
                      "gte": "2020-04-02T04:00:00.000Z",
                      "lte": null
                    }
                  }
                }
              }
            }
          }
        }
      ],
      "filter": [
        {
          "bool": {
            "must": [
              {
                "bool": {
                  "filter": []
                }
              },
              {
                "bool": {
                  "filter": []
                }
              }
            ]
          }
        }
      ]
    }
  },
  "sort": [
    {
      "nct_id": "asc"
    }
  ],
  "timeout": "11s",
  "size": 0,
  "from": 0
}'`

**Comment by hifilorau** [comment]
```curl http://localhost:9200/studies_development/_search?pretty -H 'Content-Type: application/json' -d '{
  "aggs": {
    "wiki_page_edits": {
      "nested": {
        "path": "wiki_page_edits"
      },
      "aggs": {
        "wiki_page_edits.email": {
          "filter": {
            "bool": {
              "must": [
                {
                  "bool": {
                    "must": [
                      {
                        "bool": {
                          "filter": []
                        }
                      },
                      {
                        "bool": {
                          "filter": []
                        }
                      }
                    ]
                  }
                }
              ]
            }
          },
          "aggs": {
            "wiki_page_edits.email": {
              "terms": {
                "field": "wiki_page_edits.email",
                "size": 1000000,
                "order": {
                  "_term": "asc"
                },
                "missing": "-99999999999"
              },
              "aggs": {
                "agg_bucket_sort": {
                  "bucket_sort": {
                    "from": 0,
                    "size": 25,
                    "sort": [
                      {
                        "_key": {
                          "order": "asc"
                        }
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": "*"
          }
        },
        {
          "nested": {
            "path": "wiki_page_edits",
            "query": {
              "bool": {
                "should": []
              }
            }
          }
        },
        {
          "nested": {
            "path": "wiki_page_edits",
            "query": {
              "bool": {
                "should": {
                  "range": {
                    "wiki_page_edits.created_at": {
                      "gte": "2020-04-02T04:00:00.000Z",
                      "lte": null
                    }
                  }
                }
              }
            }
          }
        }
      ],
      "filter": [
        {
          "bool": {
            "must": [
              {
                "bool": {
                  "filter": []
                }
              },
              {
                "bool": {
                  "filter": []
                }
              }
            ]
          }
        }
      ]
    }
  },
  "sort": [
    {
      "nct_id": "asc"
    }
  ],
  "timeout": "11s",
  "size": 0,
  "from": 0
}'
```

**Comment by hifilorau** [comment]
Additional info -from @Tonyynot14  " the filter does not apply correctly because the aggregation is nested and it needs to exit it somehow to apply unnested filters, I say this because if you apply a created_at filter then look and the emails it works"

**Comment by hifilorau** [comment]
From @williamhoos "by the way, the date range does seem to "apply" correctly in the search results - this query has 3 results. If I remove the date range, it has 4 results. The date facet doesn't display any values so hopefully the issue is isolated to how a nested facet pulls the available values to allow filtering on and NOT from how those values, when selected, get applied to the search results. This is encouraging and maybe points to part of the solution http://experimental.clinwiki.org/search?hash=urtFJNTH&sv=default"

**Comment by williamhoos** [comment]
Adding a more complete issue description:

The facets rely on a "and" logic across different facets. ie when filtering a crowd tag of "ALS" and then going to the Intervention facet, the list has been filtered to only contain interventions for studies tagged "ALS".  This is the desired, correct behavior and works now.

Except in the new nested facets (at least the checkbox list version, not sure about the date range).

The nested facets, currently, labeled wiki_page_edits.Email, work normally as long as no other facets are selected. When selecting any other values for any facets, the entire list of the email facet is empty.

Sample queries on experimental are in slack
