### ISSUE TITLE
Bug: Study with no brief title preventing login.

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#539]

**Comment by hifilorau** [comment]
If you reviewed a study and clinical trials were to delete it or it was deleted otherwise then it is currently preventing login. This happened on experimental when studies were deleted and reuploaded.

**Comment by williamhoos** [comment]
So if a review exists for a study that doesn't exist, what is the error and what is the plan to resolve? Is it just "reviews" or any wiki entry? I think the main scenario is that sometimes studies are entered in duplicate or are fraudulent in CTD and it takes a few days for CTG to clean them. We might create a wiki entry entry for crowd tagging in that period. How does an index and wiki entry ever get cleaned out if that is needed?
