### ISSUE TITLE
Map intl locations (need to understand google cost, maybe just index recruiting/newer studies - or pull data live when a study is requested without timing out)

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#541]

**Comment by hifilorau** [comment]
@williamhoos , @micronix calculated it will cost about $2500 to geocode the 642,000 international locations all at once. Recommended plan is to do them live and save to locations table as studies are opened.  

Cost per 1000 is $4. For first 100,000 the prices is $5. So the cost will be a little higher than 2500 as the $4 was used in the rough calculations. Doing them on the fly, would want to only geocode once when the study opens and then save to the db in the facility_locations data.

**Running Gecoding Live Plan (recommended).** 
1. Open a study, run facilities query. map through facilities and see if there is a geocoding location
2. If there is no location on a facility have the backend adds facility to geocoding queue and begin geocoding these studies. 
3. Add a message in facilities section of Study page saying geocoding processing
4.. Rerun the facilities query on the study every five seconds until all facilities are all located.

**Comment by williamhoos** [comment]
We have monthly credits at Google and can get more. I think issue before was that it crashed if query was too slow.
