### ISSUE TITLE
Replace crowd section in studies with workflow style CRUD using same components.

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#542]

**Comment by williamhoos** [comment]
Not sure we can do this until we adjust how configuration of which values show in the crowd section. I think we should hold unless you have a plan that is easy.

**Comment by hifilorau** [comment]
I do not yet, but wanted to start thinking about it and make sure @blatde91 was thinking about long term usage of his component. That crowd configuration will happen in the sites/study section right (screenshot below) @williamhoos? Probably something @micronix and I can start planning unless you want @ericharding to handle initial config for. Thinking it can work similarly to how we do agg fields and visible options for facets/presearch?

![Screen Shot 2020-05-12 at 10 44 41 AM](https://user-images.githubusercontent.com/2739321/81705986-ab88b300-943d-11ea-849c-d6b0a14558a2.png)

**Comment by williamhoos** [comment]
@ericharding is doing the mailmerge changes which will control this whole study config area. The plan is likely to allow 1-to-many study pages for subsites so there can be, for example, a summary and a detail view of the studies. The workflow configuration will also merge into the study page configuration, with workflows either being a dependency driven section based on a workflow breadcrumb being selected or a workflow specific version of the study page with dependency driven for entering the workflow. May re-evaluate useing the selection of a breadcrumb as how to "enter" workflow mode (vs some community dashboard with links driven by querystring value). Some scoping is needed.
