### ISSUE TITLE
Adding Subsite Leaderboard (admnin & public)

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#553]

**Comment by hifilorau** [comment]
@williamhoos 

@Tonyynot14 is looking into this with elastic search and will comment below. But it does seem like for the admin side it would take some work assuming we want to do this with elastic search vs querying the database so that we can do additional filtering for the admin version? Seems like admin view would need facet bar/etc. 

Doing a public leaderboard by skipping an elastic search and querying DB directly would be really straightforward. Could do something like return top 25 reviewers based on # of studies contributed along with links to their public profile pages.

**Comment by hifilorau** [comment]
New Subsite Leaderboard plan: create a new siteview type called leaderboard for public leaderboard and use the contribution facet in combination with the crowd_agg that is associated with that site to pull top contributors by contributions to a subsite . Phase 1 will just be using a presearch view with no results as a way to display the contributors. We will also create a route for the public leaderboard. 

Admin leaderboard can use same type of functionality or can probably actually just be created per site using an admin type siteview with current functionality.

**Comment by williamhoos** [comment]
So to confirm, "all" we will do is create 2 new routes/pages that list site_views that are specified to be that type? My hope/bias is that the simplest way is just make a page that shows a table of the site_views of those that includes the name and link. This allows more than one dashboard.

**Comment by williamhoos** [comment]
So "admin dashboard" page shows the list of admin_dashbaord types and the "site dashboard" shows the site_dashboard types.

**Comment by williamhoos** [comment]
and admin requires the new site_admin role when we implement that functionality.
