### ISSUE TITLE
Adding Pie Chart Facet Type

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#558]

**Comment by hifilorau** [comment]
PLAN. 
1. Create a new facet type on back-end.
2. Create PieChart AggDropDown component. 
3. Implement ReCharts PieChart in PieChart component.
4. Render only top 10 buckets by count. 
5. Make piechart sections clickable to filter studies.

**Comment by bespinosa01** [comment]
Current Tasks:
-When params update pie chart is not updating
-sorting issues 
-wiki user edits facet not working with Pie char
