### ISSUE TITLE
Move frontend to React

### ISSUE THREAD

**Issue by relwell** [clinwiki-org/clinwiki#56]
* Search works as it does now
* Login/Signup
* Study view / edit
* Anonymous users should be able to search
* Ensure tab display is still configurable (e.g. pull #42)

**Comment by williamhoos** [comment]
Part of the goal is mobile adaptive.  If the studies page layout needs to change (away from tabs, etc) with the react front end, that is fine.

**Comment by relwell** [comment]
Viewing reviews when not logged in will show the last viewed set of reviews, and cannot access reviews for a new study when not logged in.

Loading a new study should clear the reviews list and we should make sure that reviews can be viewed by users that are not logged in.

**Comment by relwell** [comment]
This one is complete
