### ISSUE TITLE
Role & Group Support

### ISSUE THREAD

**Issue by relwell** [clinwiki-org/clinwiki#58]
We need the ability to define user roles (e.g. superuser, group admin, regular user).

Users should be able to interact with one or more groups (i.e. switch between them)

Group admins and superusers should be able to configure look and feel

Users working with a given group should be able to filter search results by studies that have been reviewed by their group.

Users looking at reviews for a given study should see reviews from users in their group first.

**Comment by williamhoos** [comment]
Need to evaluate if the role and group functionality evolves to "credentials" or badges that could also be used for filtering ratings. Or is there is a better way to do this. Credentials are meant to be similar to "verified purchase" with values like 
"certified expert"
"super contributor"
"new user"
