### ISSUE TITLE
Add bar chart as facet display type.

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#588]

**Comment by williamhoos** [comment]
Not sure what drives the format but need to try to fit to the visible space, formatting doesn't look right compared to screen shot in the PR?

![image](https://user-images.githubusercontent.com/19411659/84440974-e9c5ed80-ac08-11ea-9e8f-f2690a659613.png)

http://admin.staging.clinwiki.org/search?hash=ANUr6Wwa&sv=admin_dashboard
