### ISSUE TITLE
Add new dimensions for reviews

### ISSUE THREAD

**Issue by relwell** [clinwiki-org/clinwiki#59]
Review dimensions should be a data model with a given label (e.g. "potential for cure" or "side effects"). If a group chooses to configure dimensions, then only show the dimensions associated with the group. Otherwise, show all dimensions in a review view.

Long-term, we should be able to associate review dimensions with tags as well.

**Comment by relwell** [comment]
||---|-------------------||
|| id | review_dimension ||
||---|------–------------||
|| 1  | good_for_diabetics ||
||---|--------------------||

||----------||--------------||-------||
|| review_id|| dimension_id || rating ||
|| --------  || ------------- || ------ ||
|| 234         || 1                     || 3        ||
|| --------  || ------------  || -----   ||

Once available, groups should be able to specify dimensions they want made available in the UI

**Comment by relwell** [comment]
Once the data model is available we should expose a piece of UI in reviews that lets you add one or more dimension ratings using autocomplete against a list of existing dimensions with the opportunity to add a new one

**Comment by relwell** [comment]
Add ability to associate dimensions to a given tag, and then show those dimensions by default for a given review when the study has that tag.

**Comment by relwell** [comment]
👍

**Comment by relwell** [comment]
👍

**Comment by williamhoos** [comment]
this is one of the more important things but scale of effort needs consideration.  Need to review plan and possibly do research and confirm option is best path forward that will scale and if there are other options

**Comment by williamhoos** [comment]
not sure relevant, closing
