### ISSUE TITLE
Number of Studies to Display in Study List should default to 50

### ISSUE THREAD

**Issue by tibbs001** [clinwiki-org/clinwiki#6]
It currently defaults to display 10.  Should be 50
To persist settings across session, see:  https://datatables.net/examples/basic_init/state_save.html

**Comment by williamhoos** [comment]
Also ensure selection of sort, filter and record count persists when using back button or "return to study list"

**Comment by tibbs001** [comment]
Changed dataTable parameters to save state and default number of rows to 50

**Comment by tibbs001** [comment]
Hey Willy - can you try this out to see if it behaves as you would expect
