### ISSUE TITLE
Facet pagination

### ISSUE THREAD

**Issue by relwell** [clinwiki-org/clinwiki#61]
The UI should accommodate loading additional facet data when a user interacts with that facet

**Comment by williamhoos** [comment]
👍

**Comment by williamhoos** [comment]
👍

**Comment by williamhoos** [comment]
👍

**Comment by williamhoos** [comment]
👍

**Comment by relwell** [comment]
Estimating about 5 hours worth of work. Need to create request to retrieve all pagination values in the backend, and then handle the generation of that event once the facet has been clicked.

**Comment by relwell** [comment]
Managed to get this done in more like two hours. It's on https://clinwiki-dev.herokuapp.com/ now.

**Comment by relwell** [comment]
Commits for reference: https://github.com/clinwiki-org/cw-app/commit/96316e267afc99b2f6aaf5f9859303079748f796

https://github.com/clinwiki-org/clinwiki/commit/1103e67161402940197cf1e9ae98f16c8b976745

**Comment by williamhoos** [comment]
👍
