### ISSUE TITLE
Reactions not showing unless you have made the specific reaction

### ISSUE THREAD

**Issue by bespinosa01** [clinwiki-org/clinwiki#610]
When you are not signed. in or you have not reacted to a study you cant see any of the current reactions and respective counts.

**Comment by williamhoos** [comment]
reopening for bug that a user can't "click" to increment a reaction if they haven't reacted to that study with that reaction, but rather have to use the smiley face add options.

![image](https://user-images.githubusercontent.com/19411659/85630502-bd1ac880-b641-11ea-86b8-118531ab7eab.png)

Behavior should be:

1. If study has no "like reaction", use smiley face to see menu of available reactions and add a reaction from the menu (currently works) (menu for like icon can also still work even if there are existing likes)
2. If study has any like reaction from any user, then the count of likes shows on study page (currently works)
3. If study is liked by other users only, not current user, clicking the like icon should add a like for the current user **(currently blocked)**
4. If study has been liked by current user, clicking icon should "unlike" (currently works)
