### ISSUE TITLE
Wiki style editing of annotations

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#63]
Allow wiki style editing and change tracking of the annotations area. Prefer that editing uses WYSIWYG editing vs markdown.

**Comment by relwell** [comment]
* Research existing implementations for Ruby
* Implement a WYSIWYG editor that compiles down to markdown
* Store changesets in an edits table

**Comment by relwell** [comment]
👍

**Comment by relwell** [comment]
👍

**Comment by relwell** [comment]
👍

**Comment by relwell** [comment]
👍

**Comment by relwell** [comment]
4 for the research, but then bump it down once we've commented some scope

**Comment by williamhoos** [comment]
created planning task so lowering priority

**Comment by relwell** [comment]
Next step is adding table-stye field for status and type (e.g. https://raw.githubusercontent.com/maciakl/Sample-Jekyll-Site/master/_posts/2012-01-18-hello-world.markdown) and a template wiki page for every study with brief summary pre-populated for lay summary header and a template header for pros and cons that say "add pros here" and "add cons here"
