### ISSUE TITLE
Refactor Search Page

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#631]
#688  is part of this larger card.

**Comment by Tonyynot14** [comment]
1.One of the first queries on the page is SearchPageParamsQuery on the front end and back end it is called search_params. The only thing this query does is finds a short link based hash in URL. This short link has a database table that holds the full params list and the short link hash value. 

2.SearchPageSearchQuery is executed after using the full params list, not a short_link.
-At some point in the query 100 studies are loaded then the reviews/wiki_pages for those studies is also loaded. I would guess at 
 least some of that information does not need to be loaded on that page. Including the reviews, review count and wiki_page probably will not be used unless actually on the study page of the study. 
-Page Size affects how many it loads from the study table/ but still seems to call more fields than it needs to.
-The elasticsearch call gets the nct_ids from the index for each study but seems to resolve them with SQL 

3.Then SearchPageHashMutation is ran twice which creates the shortlink that is used in the URL. This literally just either creates a new shortlink if it does not exist or updates the updated time on the already shortlink table

**Comment by Tonyynot14** [comment]
Search page study_type returns all of these columns, seeing as the only information being show is the fields as defined in the ui of customizing them they should probably be the only values loaded. 
- acronym: null

- averageRating: 0
- baselinePopulation: ""
- biospecDescription: ""
- biospecRetention: null
- briefTitle: "Congenital Adrenal Hyperplasia: Calcium Channels as Therapeutic Targets"
- completionDate: null
- completionDateType: null
- completionMonthYear: null
- dispositionFirstPostedDate: null
- dispositionFirstPostedDateType: null
- dispositionFirstSubmittedDate: null
- dispositionFirstSubmittedQcDate: null
- enrollment: null
- enrollmentType: null
- expandedAccessTypeIndividual: null
- expandedAccessTypeIntermediate: null
- expandedAccessTypeTreatment: null
- hasDmc: null
- hasExpandedAccess: "false"
- ipdAccessCriteria: null
- ipdTimeFrame: null
- ipdUrl: null
- isFdaRegulatedDevice: null
- isFdaRegulatedDrug: null
- isPpsd: null
- isUnapprovedDevice: null
- isUsExport: null
- lastKnownStatus: null
- lastUpdatePostedDate: "2005-06-24"
- lastUpdatePostedDateType: "Estimate"
- lastUpdateSubmittedDate: "2005-06-23"
- lastUpdateSubmittedQcDate: "2005-06-23"
- limitationsAndCaveats: ""
- nctId: "NCT00000102"
- nlmDownloadDateDescription: "ClinicalTrials.gov processed this data on April 30, 2020"
- numberOfArms: null
- numberOfGroups: null
- officialTitle: null
- overallStatus: "Completed"
- phase: "Phase 1/Phase 2"
- planToShareIpd: null
- planToShareIpdDescription: null
- primaryCompletionDate: null
- primaryCompletionDateType: null
- primaryCompletionMonthYear: null
- resultsFirstPostedDate: null
- resultsFirstPostedDateType: null
- resultsFirstSubmittedDate: null
- resultsFirstSubmittedQcDate: null
- reviewsCount: 0
- source: "National Center for Research Resources (NCRR)"
- startDate: null
- startDateType: null
- startMonthYear: null
- studyFirstPostedDate: "1999-11-04"
- studyFirstPostedDateType: "Estimate"
- studyFirstSubmittedDate: "1999-11-03"
- studyFirstSubmittedQcDate: "1999-11-03"
- studyType: "Interventional"
- targetDuration: null
- verificationDate: "01/31/2004"
- verificationMonthYear: "January 2004"
- whyStopped: null
- __typename: "Study"

**Comment by williamhoos** [comment]
Tony, what would it take to modify the graphql call from the results query
to pull the requested fields from elastic search?

**Comment by Tonyynot14** [comment]
@williamhoos I am starting to think it does do that actually but only a guess, I think it only hits the db when it does not know the anwser to the question because the value is not indexed. Thats just a guess though, trying to figure out a good way to test that theory

**Comment by williamhoos** [comment]
One thing should be looking at the graphql query fragment formed by
mailmerge. That should be the only thing needed for the search results and
if it does need something else, we should modify graphql and indexing to
use the index

**Comment by Tonyynot14** [comment]
https://github.com/ankane/searchkick#user-content-results Shows what I guessed is that you can tell it to load based on the elasticsearch only, which is why it does not make a call more frequently. It currently has load: false on the query

**Comment by williamhoos** [comment]
Ongoing threads in slack, placing some notes here:

SiteProviderQuery is part of performance issue and needs to be reconciled even though not explicitly part of search page

adjusting graphql to utilize elasticsearch for search results may be appropriate.

possibly "low hanging" change is to just reconcile whether a section is being displayed and use that to decide whether to run the queries needed to populate that section. Right now, it appears that even if the presearch or the results sections are hidden, the data is still retrieved and just not displayed.

**Comment by Tonyynot14** [comment]
Discovered that searchkick does in fact not have load: false enabled in the default query. So this makes it try to resolve everything in the database using just the nct_id. Every time you do a search it loads all the the study database from the database. When changing the load to false it does break the front end though but the active record database time is less because only uses database to check subdomain and create short link.

**Comment by hifilorau** [comment]
@Tonyynot14 any idea of what is breaking on the front-end, assuming a piece of data that it's asking for isn't there? Just wondering if this dovetails with @bespinosa01 reformatting that search page query to use different fragments on search and study page.

**Comment by Tonyynot14** [comment]
Yeah It would be anything on the type that uses a loader probably. Essentially the search results probably should have it own type that does not have fields except indexed one potentially and then turn the loading off. But not sure what kind of complication that would cause. But that would prevent SQL calls completely on the studies. Technically as of right now nothing is loaded from Elasticsearch except the nct_id to do the sql search. It selects all the columns for the study table in the query.

**Comment by Tonyynot14** [comment]
Which I did not fully understand till very recently.

**Comment by Tonyynot14** [comment]
1. Make new type for search_study_type ( only indexed values fields)  
- This includes only using fields that are indexed( 63 currently indexed fields)
- Need to test and make sure all the fields work and can accept null if they are null. 
-  Need a defiantive list of values that will be required for search_page so that we can make sure to index them and have fields on this type
- This study type is used in search_result_set_type which would have to be changed to elastic_study_type and that should be fine but it is used in a couple places. 
2. Turn off sql for searchkick ( load: false) 
- Add the option to the elasticsearch search query. 
3. Update front end searchpage query to use new type and not ask questions that are not in elasticsearch
4. Use mailmerge eventually using the new type
