### ISSUE TITLE
implement react-virtualized

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#640]
Would like 3 views:

- [x] cards/grid sized for 3 studies per "row" in "standard" html, responsive adaption as width changes to mobile (the masonry but with all cards/boxes having a fixed width and height at 1/3 page width and reasonable height (https://bvaughn.github.io/react-virtualized/#/components/Masonry)
- [x] card/grid sized for 1 study per row sized to page width (the "list" view - https://bvaughn.github.io/react-virtualized/#/components/List)
- [x] table https://bvaughn.github.io/react-virtualized/#/components/Table - need to figure out how we will specify the header values and the field values in mailmerge (please suggest an approach before implementing)

**Comment by bespinosa01** [comment]
A few pending open items 

- [ ] Need to add MailMerge configuration component for new card views
- [ ] Need to implement a way to specify headers for new table using markdown 
- [ ] Old table Columns sizes are off
- [ ] For now change initial query to 100

**Comment by williamhoos** [comment]
see #655 for sorting specs
