### ISSUE TITLE
Page URL / Querystring

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#652]
Move

**Comment by williamhoos** [comment]
Changes for new "pages"

**Comment by williamhoos** [comment]
Changes for new "pages" section:

1. URL path should be defined by the type of page - "study" should be the study page path (replacing the current "p/<page_name>" which was a place holder.
2. the page_name should go in the querystring so it can A) keep each study page's URL constant for indexing (ie study/<nct_id>?<querystring> and B) so the page_name can be passed as part of the link and replaced for other views of the study page.

**Comment by bespinosa01** [comment]
Items 1-3 have been taken care of by most current version of 639-islands branch. for item #4 currently if no pageview specified it defaults the pageViewUrl to a value of "test".
Tony has finished the backend portion I just need to hook up tony's work to replace the above mentioned hardcoded default.
