### ISSUE TITLE
Remove paging info from shortlink(page hash)

### ISSUE THREAD

**Issue by Tonyynot14** [clinwiki-org/clinwiki#658]
Need to remove paging information from page_hash/

Probably needs front end changes as well if it references the paging information from the hash ever

**Comment by Tonyynot14** [comment]
I have a branch but no pull request yet for this because may need front end changes but made the default behavior remove the paging information from the link. The two problems I see next are front end removing references to that and also technically old links will still have the paging information which shouldn't matter as long as the front end does not pay attention to it but still might need to be removed somehow.

**Comment by Tonyynot14** [comment]
branch is https://github.com/clinwiki-org/clinwiki/tree/658-remove-shorlink-from-hash

**Comment by hifilorau** [comment]
The backend work is done but need to integrate with new RV tables and handle pagination before we go live. This branch doesn't work but has the old table and pagination doesn't work. So as soon as we get #691 branch from @bespinosa01  will merge these branches.
