### ISSUE TITLE
Location/facilities Information tab/section and map

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#67]
Add facilities tab to studies page
List all studies with status
Have a map view option

**Comment by williamhoos** [comment]
👍

**Comment by williamhoos** [comment]
👍

**Comment by relwell** [comment]
Example: facility A is recruiting but facility B isn't

* need a way to clarify whether a facility is recruiting
* introduce a data model for study and facility to recruiting status

**Comment by williamhoos** [comment]
handled in #97
