### ISSUE TITLE
Remove site view options for old table and old cards & clean up related code.

### ISSUE THREAD

**Issue by rodctech** [clinwiki-org/clinwiki#723]
The first 2 items are the old cards and table views and can be removed (with all of their related code).

![image](https://user-images.githubusercontent.com/45049806/90803434-5848bb00-e2de-11ea-843e-fc90eb89fd66.png)

**Comment by kaveer-k** [comment]
Moved to JIRA as ticket [CW-50](https://clinwiki.atlassian.net/browse/CW-50) so closing this issue.
