### ISSUE TITLE
Annotation description input should be a textarea and sort alphabetical by label value

### ISSUE THREAD

**Issue by relwell** [clinwiki-org/clinwiki#75]

**Comment by relwell** [comment]
👍

**Comment by relwell** [comment]
👍

**Comment by williamhoos** [comment]
Also need to make the annotations area tab sort alpha (seems to sort by last updated last. Will add 1), 2), 3) in front of label names so they sort as desired.

**Comment by relwell** [comment]
This is completed and deployed to dev.

**Comment by williamhoos** [comment]
Looks good. I was updating things and the submit button seems to hang.  This occured after I added some annotations and wanted to edit the label but couldn't so I deleted the labels and re-added 3 labels. When clicking submit, nothing happens and navigating away loses the entry.  I then tried to add a review and submit button also didn't work.  

Refresh page didn't fix anything but I back out, did a refreshed search back to the same study and it worked fine and I was able to add the 3rd label? Study is below if checking logs?

http://clinwiki-dev.herokuapp.com/study/NCT02399137

**Comment by relwell** [comment]
Interesting bug on this one -- it looks like changes to studies were instantiating new connections on Redis, which resulted in errors when hitting the max number of connections, which is relatively low. I've updated the reindexing log to reuse connections with Redis that were already instantiated at startup time, and that seems to fix the bug.
