### ISSUE TITLE
Make study tabs collapsible views in the same page

### ISSUE THREAD

**Issue by relwell** [clinwiki-org/clinwiki#78]
Right now we have a set of tabs you can click to display information. We should make these collapsible views on the same page, and in the future we should be able to configure which views are minimized by default and what their ordering is.

**Comment by relwell** [comment]
👍

**Comment by relwell** [comment]
👍

**Comment by relwell** [comment]
:+1

**Comment by relwell** [comment]
👍

**Comment by relwell** [comment]
Estimating about 2 hours for this

**Comment by williamhoos** [comment]
covered in redesign #105 - closing
