### ISSUE TITLE
Planning Task - Wiki Style editing

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#81]
References #63 
Review roadmap for wiki style editing and come up with phases development approach

**Comment by relwell** [comment]
Should take about an hour to research this one

**Comment by relwell** [comment]
This looks like a good option for a markdown editor in React: https://github.com/sstur/react-rte

**Comment by relwell** [comment]
We should add this editor to reviews, but we also need a special section and data model that is just devoted to wiki data. We should have a new data model -- one per study -- that provides the ability to add a markdown wiki summary as opposed to a review or annotation. We'll call this WikiPage. Users can edit using WYSIWYG, but it will be saved as Markdown.

The WikiPage model will have an associated model called WikiPageHistory, which refers to the primary key of the wiki page id, the id of the user who made the most recent change, an optional comment the user can provide on what changed, the timestamps associated, and the diff text of the markdown of the wiki, using https://github.com/samg/diffy.

The above should take about between 6-8 hours worth of work.

Introducing a history view will probably be an extra few hours. This would provide a list of changes *to the WikiPage only*, ordered chronologically, with the ability to view the change, and to revert it.

To reduce complexity, we probably should only allow reverting the most recent change.

**Comment by relwell** [comment]
Should also reserve an hour or so for making sure we get wiki data into search

**Comment by williamhoos** [comment]
The tools look good and agree with all the diff.

Need to understand the new model plan.  My thought was that the "annotations" section would either be enabled with wiki-style capabilities or replaced by the wiki capabilities.  Not clear which is planned here so should talk through it.

Pro/Con/Lay Summary are the 3 current headings but global additions of new headings are likely (reference section, other) and sub-topic specific (genes of relevance, side effects) are needed. 

Need to understand how this adaptability fits into the plan.  I see entries in wikipedia are just a single long document for each entry but there is table of contents, etc.  I'm not sure if this is "structured" enough. I also just noticed their relatively new Inline "visual editor" they have so curious if it can be leveraged?  Seems a little quirky.

**Comment by williamhoos** [comment]
Let's plan to discuss the path forward on a call to confirm scope and options.

**Comment by relwell** [comment]
Sounds good -- I can help explain then how this stuff all works. In short, headings in MediaWiki are just a rendering artifact of Wikitext, which is a single field. It might make sense to replace annotations with the WikiPage model, and simply provide a default template for studies without a WikiPage

**Comment by williamhoos** [comment]
Makes sense.  Want to understand the shortcomings of the "artifact" for structured search capability and this may have to link to the need to allow crowd version/editing of other content like study status, site status, site contact info.

**Comment by relwell** [comment]
I think one other thing to consider is that we may want to prioritize https://github.com/clinwiki-org/clinwiki/issues/78 ahead of this so that we have a UI more amenable to making this update.

**Comment by relwell** [comment]
Proposed pre-populating wiki pages for each study based on AACT database, and then allow users to edit the Wiki Page

**Comment by relwell** [comment]
First deliverable would be a wiki page without data primed directly from AACT studies. The data would be parsed into search in the same document as the current study. We may be able to add in the custom dimensions as a markdown table inside of the wiki page depending on time.  Should take around 10 hours +/- 2 hours.
