### ISSUE TITLE
Faceting Additions

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#82]
Need to have filter by:
Study Phase
mesh term from browse_condtions is the other term to add.  I believe this is already indexed.

**Comment by relwell** [comment]
Should only be an hour, but will impact the UI. Is there a filter field we can remove?

**Comment by williamhoos** [comment]
We can drop completed date for now.  Date facets with years (vs ranges) aren't as useful anyway and not that critical.

**Comment by relwell** [comment]
Updated and pushed to clinwiki-dev
