### ISSUE TITLE
Enable ability to share a fully filtered (using facets) search with someone else via link

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#87]
Right now only the search term shows in url, so no way to, for example, send someone a link to "all recruiting pancreatic cancer trials with a certain tag and in a chosen state"

**Comment by SearchSpecifics** [comment]
With my app I programmed in Python named SearchSpecifics I scrape text and data from webpage to webpage and and "processes" them in the background for a "super" result on any subject but especially with respect to clinical trials; I'm always looking to create a link that would supersede or make moot any human interaction with a given web page.

The crux of my post here is might not the "Enable ability to share a fully filtered (using facets) search with someone else via link" be moot and everything possibly accomplished or realized by the search field alone?

I see that with "ClinWiki production": https://clinwiki-prod.herokuapp.com/search/ user entries in the "Search" result in just such a URL link.  For example a Search of California and New York results in this URL link:

https://clinwiki-prod.herokuapp.com/search/California%20New%20York

with a result count of: Showing 1 to 25 out of 12353 for California New York

Bingo! Exactly what I'm looking for!

The Search seems to be: CONJUNCTIVE or a logical AND.  Results are only trials that contain New York AND California.

The Search URL for New York alone is:

https://clinwiki-prod.herokuapp.com/search/New%20York

With a result of: Showing 1 to 25 out of 23722 for New York

Luckily adding parentheses has no effect on the result. This will prove important in a moment.

https://clinwiki-prod.herokuapp.com/search/(New%20York)

For California the search URL (of course) is:

https://clinwiki-prod.herokuapp.com/search/California

with a result of: Showing 1 to 25 out of 29183 for California

If I try to insert a logical OR by extension  either New York OR California should result in the sum of New York and California:  23722 + 29813 =  53535

Lets try it out: 

https://clinwiki-prod.herokuapp.com/search/(New%20York)%20OR%20California

Not what I expected / was looking for:

with a result of: Showing 1 to 25 out of 9086 for (New York) OR California

Now lets got to the Drop-Downs ...

On selecting  "states" the first entry in the drop down is California with a "instance count" of: 27672

That California has a different value than the standalone California and respectively New York is disconcerting in its own right but let's put that issue aside of the moment. 

New York in the drop down has a value of: 22606

So at this juncture before selecting both California and New York if the resulting count is larger than either counts respectively the drop down are inherently DISJUNCTIVE to some degree. I'm looking for an absolute degree.  If the result is smaller than either the down down is inherently CONJUNCTIVE.

Let's try it out:

the result is a "strange": Showing 1 to 25 out of 38131 expecting a 50278 if the selection are truly DISJUNCTIVE - a logical OR.

Again my question is might not there be a way to realize everything by the Search field once the counts between the drop-downs are fixed or reconciled? Might not it be possible to implement a "functional OR" in the search leaving the drop downs moot and just a useful feature for human web page interaction?

**Comment by williamhoos** [comment]
Implemented by ericharding with pull https://github.com/clinwiki-org/clinwiki/commit/5ea86b840d0fbd8925902674ac6cf90b40ce7af8
